/**
 * User Service
 * Service for managing users
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type sent to login/invite method
 */
export interface LoginInviteBodyRequestBody { 
    /**
     * New user email
     */
    email: string;
    /**
     * ID of the organisation he was invited to
     */
    organisationID: string;
    /**
     * New user password
     */
    password: string;
}

