/**
 * User Service
 * Service for managing users
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersInviteResponseBody { 
    /**
     * Status of the performed request
     */
    status?: UsersInviteResponseBody.StatusEnum;
}
export namespace UsersInviteResponseBody {
    export type StatusEnum = 'success' | 'failure';
    export const StatusEnum = {
        Success: 'success' as StatusEnum,
        Failure: 'failure' as StatusEnum
    };
}


