/**
 * User Service
 * Service for managing users
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginInviteBodyRequestBody } from './loginInviteBodyRequestBody';


export interface UsersInviteRequestBody { 
    user?: LoginInviteBodyRequestBody;
}

